image: continuumio/miniconda3

unit:
  script:
  - conda env create -q -f environment_cpu.yml
  - source activate net_test
  - conda install -yq pytest-cov
  - py.test -v --cov=utils

training:
  script:
  - conda env create -q -f environment_cpu.yml
  - source activate net_test
  - python training.py -i tests/data/dataset/ -o "test" --conv_channels 2 2 --dense_sizes 2 2 --num_epochs 2 --rotations 0 1
  when: manual

prediction:
  script:
  - conda env create -q -f environment_cpu.yml
  - source activate net_test
  - python prepare.py -l tests/data/complexes/*/*_ligand.mol2 -p tests/data/complexes/*/*_pocket.mol2 -o test_input.hdf
  - python predict.py -i test_input.hdf -o test_predictions.csv
  when: manual
